;;; lxc-tramp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from lxc-tramp.el

(autoload 'lxc-tramp-add-method "lxc-tramp" "\
Add lxc tramp method.")
(eval-after-load 'tramp '(progn (lxc-tramp-add-method) (tramp-set-completion-function lxc-tramp-method lxc-tramp-completion-function-alist)))
(register-definition-prefixes "lxc-tramp" '("lxc-tramp-"))

;;; End of scraped data

(provide 'lxc-tramp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lxc-tramp-autoloads.el ends here
